---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# **The workflow**

This is the general workflow:

1.  Open a new or existing R Markdown file in `analysis/` (optionally using [`wflow_open()`](https://workflowr.github.io/workflowr/reference/wflow_open.html))

2.  Perform your analysis in the R Markdown file (For RStudio users: to quickly develop the code I recommend executing the code in the R console via Ctrl-Enter to send one line or Ctrl-Alt-C to execute the entire code chunk)

3.  Run [`wflow_build()`](https://workflowr.github.io/workflowr/reference/wflow_build.html) to view the results as they will appear on the website (alternatively press the Knit button in RStudio)

4.  Go back to step 2 until you are satisfied with the result

5.  Run [`wflow_publish()`](https://workflowr.github.io/workflowr/reference/wflow_publish.html) to commit the source files (R Markdown files or other files in `code/`, `data/`, and `output/`), build the HTML files, and commit the HTML files

6.  Push the changes to GitHub or GitLab with [`wflow_git_push()`](https://workflowr.github.io/workflowr/reference/wflow_git_push.html) (or `git push` in the Terminal)

7.  `wflow_publish(republish=T, message = "Republish entire site")`

    `# 1) Lấy toàn bộ file Rmd trong analysis`

    `all_files <- list.files("analysis", pattern = "\\.Rmd$", full.names = TRUE)`

    `# 2) Loại file lỗi ra`

    `good_files <- setdiff(all_files, "analysis/trang_loi.Rmd")`

    `# 3) Republish chỉ các file còn lại`

    `wflow_publish(`

    `files = good_files,`

    `republish = TRUE,`

    `combine = "and",`

    `message = "Republish site except broken page"`

    `)`

    **Chỉ publish những file ngon :** `good_files <- c(`

    `"analysis/index.Rmd",`

    `"analysis/about.Rmd",`

    `"analysis/license.Rmd",`

    `"analysis/4_Exercice.Rmd",`

    `"analysis/EDC_Jade.Rmd"`

    `)`

    `wflow_publish(`

    `files = good_files,`

    `republish = TRUE,`

    `combine = "and",`

    `message = "Republish selected working pages"`

    `)`

This ensures that the code version recorded at the top of an HTML file corresponds to the state of the Git repository at the time it was built.

The only exception to this workflow is if you are updating the aesthetics of your website (e.g. anytime you make edits to`analysis/_site.yml`). In this case you’ll want to update all the published HTML files, regardless of whether or not their corresponding R Markdown files have been updated. To republish every HTML page, run [`wflow_publish()`](https://workflowr.github.io/workflowr/reference/wflow_publish.html) with`republish = TRUE`. This behavior is only previewed below by specifying `dry_run = TRUE`.
